
pool:
  name: UK Agent Pools
  #vmImage: ubuntu-latest

jobs:
  - job: BuildDocker
    steps:
      - script: dir
      
  - job: Foo
    steps:
    - script: dir
    - script: echo $(IMAGE_NAME)
      condition: always()

